# Generated by Django 6.0.5 on 2026-05-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('highest_qualification', models.CharField(help_text='e.g. Plus Two, B.Sc, Diploma', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Any specific questions or areas of interest.')),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved / Closed')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admission officers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Admission Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
