# Generated by Django 6.0.5 on 2026-05-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Total years of professional experience'),
        ),
    ]
