# Generated by Django 6.0.5 on 2026-05-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('duration_years', models.PositiveIntegerField(default=3)),
                ('total_semesters', models.PositiveIntegerField(default=6)),
                ('intake_capacity', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutions.institution')),
            ],
            options={
                'unique_together': {('department', 'course_code'), ('institution', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField()),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'semester_number', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=50)),
                ('credits', models.PositiveIntegerField(default=4)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=4)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_faculty', models.ManyToManyField(blank=True, related_name='assigned_subjects', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.semester')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
                'unique_together': {('semester', 'subject_code')},
            },
        ),
    ]
