# Generated by Django 6.0.5 on 2026-05-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course', 'semester_number')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='academic_year',
        ),
    ]
