# Generated by Django 6.0.5 on 2026-05-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_semester_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed overview of the course.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Eligibility criteria for admission.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='icon_class',
            field=models.CharField(default='bi-mortarboard', help_text='Bootstrap icon class (e.g. bi-laptop, bi-shield-lock, bi-cpu).', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this course on the public homepage featured section.'),
        ),
    ]
