# Generated by Django 6.0.5 on 2026-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_description_course_eligibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
    ]
