# Generated by Django 6.0.5 on 2026-05-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('period_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='students.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='courses.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Timetable Slot',
                'verbose_name_plural': 'Timetable Slots',
                'constraints': [models.UniqueConstraint(fields=('batch', 'day_of_week', 'period_number'), name='uniq_timetable_batch_day_period')],
            },
        ),
    ]
