# Generated by Django 6.0.5 on 2026-05-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_code', models.CharField(max_length=50, unique=True)),
                ('location', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.OneToOneField(blank=True, limit_choices_to={'role': 'INSTITUTION_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_of', to=settings.AUTH_USER_MODEL)),
                ('vice_principal', models.OneToOneField(blank=True, limit_choices_to={'role': 'INSTITUTION_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_principal_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
